# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main


resources:
- repo: self

strategy:
  matrix:
    Linux:
      imageName: 'ubuntu-20.04'
      python.version: '3.9'
  maxParallel: 3

pool:
  vmImage: $(imageName)

variables:
  tag: '$(Build.BuildId)'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 17.09.0-ce
    releaseType: stable

- script: |
    sh install.sh
  displayName: 'Build Docker Image'

- script: |
    sh run.sh /$(pwd)/app/test
  displayName: 'Run API'

- script: |
    sh cleanup.sh
  displayName: 'Teardown Docker'

- script: |
    pip install -r requirements_dev.txt
    mv app/homedir app/homedir2
    mv app/test app/homedir
    nohup uvicorn app.main:app --port 8000 &
    pytest test.py -s -v
  displayName: 'start up local server for tests'
  