# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

strategy:
  matrix:
    Linux:
      imageName: 'ubuntu-20.04'
  maxParallel: 3

pool:
  vmImage: $(imageName)

variables:
  tag: '$(Build.BuildId)'


steps:
- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 17.09.0-ce
    releaseType: stable

- script: |
    sh install.sh
  displayName: 'Build Docker Image'

- script: |
    sh run.sh /app/test
  displayName: 'Run API'